export type PriceVerificationStage = "prescreen" | "batchReview" | "sourcing";

export type StageDefinition = { id: PriceVerificationStage; number: string; title: string; description: string };

export const priceVerificationStages: StageDefinition[] = [
  { id: "prescreen", number: "01", title: "数据初筛", description: "设置申报价门槛，插件采集本页数据先初筛" },
  { id: "batchReview", number: "02", title: "选择并图搜", description: "勾选 SKC 后直接执行图片图搜" },
  { id: "sourcing", number: "03", title: "货源关联", description: "查看候选、关联并入库 1688 货源" },
];

export type PrescreenSettings = { workspace_id: string; min_adjusted_price_cny?: string | number | null; updated_at?: string; updated_by?: string };

export type PluginBrowserTab = { title: string; host: string; active: boolean };
export type PluginSession = { id: string; browser: string; plugin_version: string; capabilities: Record<string, unknown>; status: string; last_seen_at: string; tab_title?: string; tab_host?: string; tab_count?: number; tabs?: PluginBrowserTab[] };
export type PluginCommand = { command_id: string; session_id: string; command_type: string; status: string; created_at: string; updated_at: string; payload?: Record<string, unknown>; result?: Record<string, unknown> };
export type QuoteRun = { run_id: string; command_id: string; status: string; item_count: number; captured_at: string };
export type QuoteCaptureBatch = { batch_id: string; name: string; store_name?: string; is_current: boolean; chunk_count: number; quote_count: number; skc_count?: number; snapshot_count: number; updated_at: string };
export type QuoteBatchSkuPrice = { sku_id: string; sku_attribute_text?: string; original_declared_price_cny?: string | number | null; adjusted_declared_price_cny?: string | number | null; new_declared_price_cny?: string | number | null };
export type QuoteBatchReviewItem = { skc_id: string; quote_keys: string[]; product_title: string; main_image_url: string; official_link_url: string; site: string; source_confidence: string; authenticity_status: string; sku_count: number; sku_prices: QuoteBatchSkuPrice[]; original_min?: string | number | null; original_max?: string | number | null; adjusted_min?: string | number | null; adjusted_max?: string | number | null };
export type BatchSelection = { id: number; batch_id: string; skc_id: string; quote_keys: string[]; product_title: string; main_image_url: string; official_link_url: string; site: string; source_confidence: string; authenticity_status: string; sku_prices: QuoteBatchSkuPrice[]; original_min?: string | number | null; original_max?: string | number | null; adjusted_min?: string | number | null; adjusted_max?: string | number | null; max_candidates: number; status: "pending" | "retained" | "deleted"; draft_id?: number | null; draft_created?: boolean; created_at?: string; updated_at?: string };
export type QuoteItem = { quote_key: string; product_title: string; main_image_url: string; official_link_url: string; skc_id: string; sku_id: string; site: string; original_declared_price_cny?: string | number | null; adjusted_declared_price_cny?: string | number | null; new_declared_price_cny?: string | number | null; source_confidence: string; authenticity_status: string; completeness_score: number; missing_fields: string };
export type QuoteDecision = { quote_key: string; decision: "retained" | "rejected"; note: string; revision: number };
export type SourceCandidate = { source_title?: string; source_platform?: string; source_url?: string; source_price_cny?: string | number; price?: string | number; promotion_price?: string | number; image_search_rank?: number; image_similarity_score?: number | null; image_similarity_method?: string; image_similarity_verified?: boolean; image_similarity_fallback?: boolean; image_similarity_selected?: boolean; image_similarity_fallback_reason?: string; title_evidence_status?: "compatible" | "missing" | "conflict"; title_evidence_reasons?: string[]; sales?: string | number; offer_id?: string; source_decision?: string; main_image_url?: string; moq?: string | number | null; domestic_freight?: string | number | null; weight_kg?: string | number | null; sku_attributes?: string; source_channel?: "image" | "manual" | ""; manual_lookup?: boolean; profit?: SourceTopProfit | null };
export type SourceTopProfit = { available: boolean; reason?: string; site?: string; selling_price?: string | number; cost_price?: string | number; weight_kg?: string | number; source_price?: number; moq?: number; domestic_freight?: number | null; domestic_fee?: string | number; shipping_subsidy?: string | number; shipping_cost?: string | number; end_fee?: string | number; total_cost?: string | number; gross_profit?: string | number; net_profit?: string | number; profit_rate?: string | number; qualified?: boolean; qualification?: string };
export type ImageSearchAudit = { downloaded: boolean; uploaded: boolean; searched: boolean; reference_image_url?: string; image_size_bytes?: number | null; download_elapsed_ms?: number | null; upload_elapsed_ms?: number | null; search_elapsed_ms?: number | null; request_id?: string; captured_at?: string };
export type DistractorSuppression = { method?: string; available?: boolean; applied?: boolean; distractor_count?: number; fallback?: string; reason?: string };
export type VisualVerification = { method?: string; threshold?: number; input_count?: number; verified_count?: number; fallback_count?: number; rejected_count?: number; unavailable_count?: number; reference_available?: boolean; elapsed_ms?: number; distractor_suppression?: DistractorSuppression; title_evidence?: { compatible?: number; missing?: number; conflict?: number } };
export type SourcePreviewItem = { quote_key: string; skc_id?: string; product_title: string; main_image_url?: string; source_search_status: string; source_search_error?: string; image_search_audit?: ImageSearchAudit; visual_verification?: VisualVerification; total_elapsed_ms?: number | null; max_candidates?: number; candidates: SourceCandidate[]; all_candidates?: SourceCandidate[]; ranked_candidates?: SourceCandidate[]; top_profit?: SourceTopProfit | null; profit_context?: { site?: string; selling_price?: string | number | null; weight_kg?: string | number } | null };
export type SourcePreviewSkcGroup = { skc_id: string; quote_keys: string[]; sku_ids: string[]; items: SourcePreviewItem[] };
export type SourcePreview = { items: SourcePreviewItem[]; skc_groups?: SourcePreviewSkcGroup[]; ranking_mode?: "image_order"; candidate_limit?: number; counts: { candidate_count?: number; failed_quotes?: number; [key: string]: number | undefined }; employee_action_summary?: { message?: string } };
export type SkcSourceLink = { id: number; batch_id: string; skc_id: string; offer_id: string; source_url: string; source_title: string; main_image_url: string; price_cny?: string | number | null; weight_kg?: string | number | null; moq?: string | number | null; domestic_freight_cny?: string | number | null; source_decision: string; note?: string; status: "active" | "removed"; created_at?: string; updated_at?: string; product_title?: string; site?: string; selling_price?: string | number | null; profit?: SourceTopProfit | null };
export type SourceCandidateSelection = { skc_id: string; offer_id: string; source_url: string; source_title?: string; main_image_url?: string; price_cny?: string | number | null; weight_kg?: string | number | null; moq?: string | number | null; domestic_freight_cny?: string | number | null; source_decision?: string };
export type ProductLibrarySource = { source_url?: string; source_title?: string; main_image_url?: string; offer_id?: string; price_cny?: string | number | null; moq?: string | number | null; domestic_freight_cny?: string | number | null; profit?: SourceTopProfit | null };
export type ProductLibraryMatch = { id: number; skc: string; site?: string; selling_price?: string | number; source_url?: string; source_main_image_url?: string; source_groups?: ProductLibrarySource[]; net_profit?: string | number; profit_rate?: string | number };
export type BatchSourcingState = { selected_skc_ids: string[]; unresolved_skc_ids: string[]; matched_products: ProductLibraryMatch[]; preview: SourcePreview | null; selected_candidates: SourceCandidateSelection[]; updated_at?: string };
