import { useState } from "react";
import type { QuoteDecision, QuoteItem } from "../types";

type Props = { runId: string; quotes: QuoteItem[]; decisions: Record<string, QuoteDecision>; busyKey: string; onDecide: (quoteKey: string, decision: QuoteDecision["decision"], note: string) => void; onExport: () => void };

export function QuoteReviewPanel({ runId, quotes, decisions, busyKey, onDecide, onExport }: Props) {
  const [notes, setNotes] = useState<Record<string, string>>({});
  const retained = Object.values(decisions).filter((item) => item.decision === "retained").length;
  const rejected = Object.values(decisions).filter((item) => item.decision === "rejected").length;
  return <section className="price-verification-panel"><div className="price-verification-panel-heading"><div><h2>人工确认报价</h2><p>报价批次到达后，逐条确认是否保留；已保留商品可进入后续货源匹配。</p></div><div className="price-verification-heading-actions"><button className="price-verification-secondary-button" onClick={onExport} disabled={!runId}>⇩ 导出报价</button></div></div>
    <div className="price-verification-review-summary"><div><span>当前报价批次</span><strong>{runId ? quotes.length : "等待采集"}</strong></div><div><span>已保留</span><strong>{retained}</strong></div><div><span>已拒绝</span><strong>{rejected}</strong></div><div><span>待确认</span><strong>{Math.max(0, quotes.length - retained - rejected)}</strong></div></div>
    {quotes.length ? <div className="price-verification-quote-list">{quotes.map((quote) => { const decision = decisions[quote.quote_key]; const value = quote.new_declared_price_cny ?? quote.adjusted_declared_price_cny ?? quote.original_declared_price_cny ?? "—"; return <article className="price-verification-quote-card" key={quote.quote_key}><div className="price-verification-quote-image">{quote.main_image_url ? <img src={quote.main_image_url} alt="" referrerPolicy="no-referrer" /> : "无图"}</div><div className="price-verification-quote-body"><strong>{quote.product_title || "未命名商品"}</strong><span>{quote.skc_id || quote.sku_id || quote.quote_key} · {quote.site || "站点待确认"}</span><b>¥ {value}</b><small>证据：{quote.source_confidence || "待确认"} · {quote.authenticity_status || "—"}</small></div><div className="price-verification-decision"><textarea aria-label="审核备注" value={notes[quote.quote_key] ?? decision?.note ?? ""} onChange={(event) => setNotes((current) => ({ ...current, [quote.quote_key]: event.target.value }))} placeholder="可选备注" /><div><button onClick={() => onDecide(quote.quote_key, "retained", notes[quote.quote_key] ?? decision?.note ?? "")} disabled={busyKey === quote.quote_key} className={decision?.decision === "retained" ? "is-selected" : ""}>保留</button><button onClick={() => onDecide(quote.quote_key, "rejected", notes[quote.quote_key] ?? decision?.note ?? "")} disabled={busyKey === quote.quote_key} className={decision?.decision === "rejected" ? "is-selected reject" : ""}>拒绝</button></div></div></article>; })}</div> : <div className="price-verification-empty-result"><span>◇</span><div><h3>等待核价采集结果</h3><p>插件完成采集后，这里会显示主图、商品标识、报价和证据状态。你可以对每条报价保留或拒绝，并记录审核备注。</p></div></div>}
  </section>;
}
